### ISSUE TITLE
How to disable crash reporting for TestFlight?

### ISSUE THREAD

**Issue by cheenu** [HipByte/motion-testflight#31]
It looks like this gem generates the initialization code into testflight_launcher.rb which is generated every time rake is run.

So I'm unable to add any code to this file e.g. TestFlight.setOptions(...)

How do I add this code? Is the testflight_launcher.rb code run before or after didFinishLaunchingWithOptions?

**Comment by christos** [comment]
Hello @cheenu 

As you might have guessed, `testflight_launcher.rb` is indeed loaded before `didFinishLaunchingWithOptions` is called. The Ruby code in `testflight_launcher.rb` is evaluated when the file is loaded, as it is inline in the file.

Unfortunately this means `takeOff` is called before you get a chance to set any options, which you must do **before** calling `takeOff`

Caveat emptor

**Comment by cheenu** [comment]
Hi @christos 

Thanks for the reply with the clarification! Looks like the only option then is monkey patching the `create_launcher` method to manually add the options I need.

Closing this issue but hopefully someone who's more experienced than me implements an elegant way to set options in motion-testflight. :smiley:

**Comment by markrickert** [comment]
Hey guys, also make sure to be using @hboon's fork that only calls `TestFlight.takeOff` once per load instead of every time the app enters the foreground. See #27 for reference and how to put it in your gemfile.

@Watson1978 any chance of getting this merged into master and a new version of the gem released to fix this issue?
